- atlas/data_source_atlas_schema.go
- atlas/data_source_atlas_schema_test.go
- atlas/resource_atlas_schema_test.go
- docs/data-sources/schema.md
- docs/index.md
- docs/resources/schema.md
- examples/data-sources/atlas_schema/main.tf
- examples/main.tf
- examples/provider/basic/main.tf
- examples/provider/main.tf
- examples/resources/atlas_schema/main.tf
`hcl` -> `src`  
`normal_hcl` -> `hcl`
> refactor data source schema

- docs/resources/schema.md
- go.mod
- go.sum
- internal/provider/atlas_schema_resource.go
- internal/provider/atlas_schema_resource_test.go
> resource/schema: support exclude attribute

- internal/provider/atlas_schema_resource.go
- internal/provider/atlas_schema_resource_test.go
> resource/schema: remove cred from ID

- internal/provider/atlas_schema_resource.go
- internal/provider/atlas_schema_resource_test.go
> resource/schema: print raw sql

- .gitignore
- go.mod
- internal/provider/provider.go
- internal/provider/provider_test.go
- internal/vercheck/notification.tmpl
- internal/vercheck/vercheck.go
- internal/vercheck/vercheck_test.go
- main.go
> provider: added vercheck call

- .gitignore
- .goreleaser.yml
> ci: bundle atlas-cli with provider

- internal/provider/atlas_migration_resource.go
> r/migration: don't plan on unknown URL

- internal/provider/atlas_migration_resource_test.go
- internal/provider/atlas_schema_resource_test.go
> test: added test case for unknown url

- internal/provider/atlas_schema_resource.go
fix: https://github.com/ariga/terraform-provider-atlas/issues/41
> r/schema: fixed falsy warning for dev_url

- internal/atlas/atlas.go
> provider: fixed execute path

- internal/provider/atlas_migration_resource.go
- internal/provider/atlas_migration_resource_test.go
> r/migration: handle non-existing schema

- go.mod
- go.sum
> chore: upgrade atlas

- go.mod
- internal/provider/provider.go
> provider: fixed vercheck calls

- go.mod
- go.sum
- internal/provider/atlas_migration_resource_test.go
> chore: upgrade latest atlas

- internal/provider/atlas_migration_data_source.go
- internal/provider/atlas_migration_resource.go
- internal/provider/atlas_schema_data_source.go
- internal/provider/atlas_schema_resource.go
- internal/provider/provider.go
> all: fixed dev-url warning

- README.md
- docs/index.md
- examples/provider/provider.tf
- internal/atlas/atlas.go
> provider: support docker as dev-url

- internal/provider/atlas_schema_resource.go
- internal/provider/atlas_schema_resource_test.go
> resource/schema: fixed schema for drop resources

- .goreleaser.yml
Fix: https://github.com/ariga/terraform-provider-atlas/issues/72
> atlas: use musl build for linux

- .github/workflows/ci.yml
- docs/resources/schema.md
- go.mod
- go.sum
- integration-tests/concurrent_index-policy/main.tf
- integration-tests/concurrent_index-policy/schema-1.hcl
- integration-tests/concurrent_index-policy/schema-2.hcl
- internal/provider/atlas_schema_resource.go
- internal/provider/template_test.go
- internal/provider/templates/atlas_schema.tmpl
> schema: add concurrent_index policy

- .github/workflows/ci.yml
- go.mod
- go.sum
- **chore: upgrade atlas and SDK**
- **.github/workflows: fixed sqlserver2022 break**
> chore: upgrade atlas and SDK

- internal/provider/atlas_migration_data_source.go
- internal/provider/atlas_migration_resource.go
- internal/provider/atlas_migration_resource_test.go
- internal/provider/atlas_schema_data_source.go
- internal/provider/atlas_schema_resource.go
- internal/provider/atlas_schema_resource_test.go
- internal/provider/builder.go
- internal/provider/builder_test.go
- internal/provider/provider.go
- internal/provider/provider_test.go
This PR prepare for the PR https://github.com/ariga/terraform-provider-atlas/pull/150, which actual allow the user config the `config` attribute, and it will have new tests for the new behavior.
This PR only changes internal stuff so all current test should pass.
> all: refactor for custom `atlas.hcl`

- internal/provider/atlas_migration_data_source.go
- internal/provider/atlas_migration_resource.go
- internal/provider/atlas_schema_data_source.go
- internal/provider/atlas_schema_resource.go
- internal/provider/atlas_schema_resource_test.go
- internal/provider/builder.go
- internal/provider/provider.go
- **provider/build: add searchBlock helper**
- **all: uniform the workspace bootstrap process**
> all: uniform the workspace bootstrap process

- internal/provider/atlas_migration_data_source.go
- internal/provider/atlas_migration_resource.go
- internal/provider/atlas_migration_resource_test.go
- internal/provider/atlas_schema_data_source.go
- internal/provider/atlas_schema_resource.go
- internal/provider/builder.go
- internal/provider/builder_test.go
- internal/provider/provider.go
> all: validate `dev_url` using the generated config

- internal/provider/atlas_migration_data_source.go
- internal/provider/atlas_migration_resource.go
- internal/provider/atlas_schema_data_source.go
- internal/provider/atlas_schema_resource.go
- internal/provider/provider.go
This pull request focuses on refactoring the `Workspace` method across multiple files to improve the management of temporary directories and clients. The main changes involve returning a `Workspace` struct that contains all the necessary data and a cleanup function, instead of using separate variables for configuration and the working directory
> internal/provider: refactor workspace handling to encapsulate project config and workdir

- internal/provider/atlas_schema_resource.go
- internal/provider/atlas_schema_resource_test.go
This PR adds logic to sync the schema to Atlas Cloud every time an approval plan is created. This will allow users to edit the plan locally.
> internal/provider: sync schema to cloud when creating approval plan
